/**
 * Turns CREDITS.json into a typed module the app can import.
 *
 * CREDITS.json lives beside the images so it stays hand-editable, but it sits
 * under public/ where a direct import would both bypass type checking and ship
 * the file twice. Generating a module keeps one source of truth.
 */
import fs from 'fs/promises';
import path from 'path';

const CREDITS_PATH = path.join(process.cwd(), 'public', 'uploads', 'external', 'CREDITS.json');
const OUTPUT_PATH = path.join(process.cwd(), 'src', 'mediaCredits.ts');

type Credit = {
  localPath: string;
  host: string;
  license: string;
  attribution: string;
};

async function main() {
  const credits: Credit[] = JSON.parse(await fs.readFile(CREDITS_PATH, 'utf-8'));

  // Only what the UI needs: the path and the line to show under the image.
  const entries = credits
    .filter((credit) => credit.attribution)
    .map((credit) => `  ${JSON.stringify(credit.localPath)}: ${JSON.stringify(credit.attribution)},`)
    .join('\n');

  const module = `// Generated by scripts/generate-credits-module.ts — do not edit by hand.
// Source of truth: public/uploads/external/CREDITS.json
// Regenerate with: npm run credits

const CREDITS: Record<string, string> = {
${entries}
};

/**
 * Attribution line for a locally hosted image, or null when none is required.
 * CC BY-SA obliges us to credit the author wherever the image appears, and the
 * obligation follows the image rather than the host.
 */
export function creditFor(src: string | undefined | null): string | null {
  if (!src) return null;
  const withoutQuery = src.split('?')[0];
  return CREDITS[withoutQuery] ?? null;
}
`;

  await fs.writeFile(OUTPUT_PATH, module, 'utf-8');
  console.log(
    `src/mediaCredits.ts: ${credits.filter((c) => c.attribution).length}/${credits.length} bản ghi có attribution`
  );
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
