// Generated by scripts/generate-credits-module.ts — do not edit by hand.
// Source of truth: public/uploads/external/CREDITS.json
// Regenerate with: npm run credits

const CREDITS: Record<string, string> = {
  "/uploads/external/070237d365a1.jpg": "Ảnh: Unsplash",
  "/uploads/external/0d4c09ff3ef0.jpg": "Ảnh: senngokujidai4434 — CC BY 2.0, qua Wikimedia Commons",
  "/uploads/external/1257bbfbccfb.jpg": "Ảnh: Unsplash",
  "/uploads/external/143a201f9dac.jpg": "Ảnh: Unsplash",
  "/uploads/external/22b49173df55.jpg": "Ảnh: trungydang — CC BY 3.0, qua Wikimedia Commons",
  "/uploads/external/24f78b813a4f.jpg": "Ảnh: Unsplash",
  "/uploads/external/281474115b74.jpg": "Ảnh: Unsplash",
  "/uploads/external/2f331a9cff29.jpg": "Ảnh: Unsplash",
  "/uploads/external/33679cf1e5a9.jpg": "Ảnh: Unsplash",
  "/uploads/external/34ecd151e0c4.jpg": "Ảnh: Bùi Thụy Đào Nguyên — CC BY-SA 3.0, qua Wikimedia Commons",
  "/uploads/external/355e36c2d702.jpg": "Ảnh: Nguyễn Thanh Quang — CC BY-SA 3.0, qua Wikimedia Commons",
  "/uploads/external/3853e8267bed.jpg": "Ảnh: Bùi Thụy Đào Nguyên — CC BY-SA 3.0, qua Wikimedia Commons",
  "/uploads/external/3b9f45655bcf.jpg": "Ảnh: Unsplash",
  "/uploads/external/3e15f452ff6b.jpg": "Ảnh: Unsplash",
  "/uploads/external/3e82fbf24e8d.jpg": "Ảnh: Unsplash",
  "/uploads/external/4d9633d557ee.jpg": "Ảnh: Unsplash",
  "/uploads/external/5c7e7cbb99df.jpg": "Ảnh: Bùi Thụy Đào Nguyên — CC BY-SA 3.0, qua Wikimedia Commons",
  "/uploads/external/5d49c81dc807.jpg": "Ảnh: Unsplash",
  "/uploads/external/5eae9e5b58fa.jpg": "Ảnh: Unsplash",
  "/uploads/external/63d97446637f.jpg": "Ảnh: Daderot — CC0, qua Wikimedia Commons",
  "/uploads/external/63e097cd5edc.jpg": "Ảnh: Unsplash",
  "/uploads/external/6976f3dac1e0.jpg": "Ảnh: Ian Armstrong from Travelling the world at moment, Australia — CC BY-SA 2.0, qua Wikimedia Commons",
  "/uploads/external/7abe2e9e3c93.jpg": "Ảnh: Diego Delso — CC BY-SA 3.0, qua Wikimedia Commons",
  "/uploads/external/83fd016f33a8.jpg": "Ảnh: Unsplash",
  "/uploads/external/86e8394d0989.jpg": "Ảnh: Unsplash",
  "/uploads/external/9644f86a7b5e.jpg": "Ảnh: Unsplash",
  "/uploads/external/9734d76f9fad.jpg": "Ảnh: Unsplash",
  "/uploads/external/9ab1e824c884.jpg": "Ảnh: Suicasmo — CC BY-SA 4.0, qua Wikimedia Commons",
  "/uploads/external/a1e4941a7477.jpg": "Ảnh: Gary Todd from Xinzheng, China — CC0, qua Wikimedia Commons",
  "/uploads/external/a4419c1d52ed.jpg": "Ảnh: Unsplash",
  "/uploads/external/a953a61daafc.jpg": "Ảnh: Diego Delso — CC BY-SA 3.0, qua Wikimedia Commons",
  "/uploads/external/aec1207e6554.jpg": "Ảnh: Unsplash",
  "/uploads/external/b08281fd0cd8.jpg": "Ảnh: Unsplash",
  "/uploads/external/b122cc5cb524.jpg": "Ảnh: MekkongHero — CC0, qua Wikimedia Commons",
  "/uploads/external/b79df3e27783.jpg": "Ảnh: Unsplash",
  "/uploads/external/b81340493a2a.jpg": "Ảnh: Christophe95 — CC BY-SA 4.0, qua Wikimedia Commons",
  "/uploads/external/bdd4700146f1.jpg": "Ảnh: Tho nau — CC BY-SA 3.0, qua Wikimedia Commons",
  "/uploads/external/c561cd48f545.jpg": "Ảnh: Unsplash",
  "/uploads/external/d06e10e91ce6.jpg": "Ảnh: Unsplash",
  "/uploads/external/d8f33c48cc5c.jpg": "Ảnh: Unsplash",
  "/uploads/external/ddaaa1e2c3e1.jpg": "Ảnh: Phương Huy (thảo luận) — Public domain, qua Wikimedia Commons",
  "/uploads/external/de0c1acc0e4c.jpg": "Ảnh: Unsplash",
  "/uploads/external/df6ae223bb5a.jpg": "Ảnh: Unsplash",
  "/uploads/external/e6e6279b9ff6.jpg": "Ảnh: Unsplash",
  "/uploads/external/e9ecdbb6aaef.jpg": "Ảnh: Unsplash",
  "/uploads/external/eacab32897a9.jpg": "Ảnh: nosarose — CC BY-SA 2.0, qua Wikimedia Commons",
  "/uploads/external/ef3b0ad325be.jpg": "Ảnh: Unsplash",
  "/uploads/external/fa19227bacc9.jpg": "Ảnh: Huỳnh Vĩ Nhơn — CC BY-SA 4.0, qua Wikimedia Commons",
  "/uploads/external/fa2e55bb77b9.jpg": "Ảnh: Unsplash",
  "/uploads/external/88a32c12ebb3.jpg": "Ảnh: choi kwangmo — CC0, qua Wikimedia Commons",
  "/uploads/external/0aad9df07334.jpg": "Ảnh: Andy Li — CC0, qua Wikimedia Commons",
  "/uploads/external/46b13b6114de.jpg": "Ảnh: Yun Huang Yong from Harbord, Australia — CC BY 2.0, qua Wikimedia Commons",
  "/uploads/external/0bbfd3fd8d0d.jpg": "Ảnh: Andy Li — CC0, qua Wikimedia Commons",
  "/uploads/external/56e72ea5b61d.jpg": "Ảnh: Andy Li — CC0, qua Wikimedia Commons",
  "/uploads/external/9a224a89efcf.jpg": "Ảnh: Hermann Luyken — CC0, qua Wikimedia Commons",
  "/uploads/external/1d2edace9c5d.jpg": "Ảnh: Andy Li — CC0, qua Wikimedia Commons",
  "/uploads/external/c6c447a725a8.jpg": "Ảnh: Andy Li — CC0, qua Wikimedia Commons",
  "/uploads/external/a38f69f72eb6.jpg": "Ảnh: Phương Huy — CC0, qua Wikimedia Commons",
  "/uploads/external/821d9077c0c7.jpg": "Ảnh: Tokeisan at Vietnamese Wikipedia — Public domain, qua Wikimedia Commons",
  "/uploads/external/3c187490bf80.jpg": "Ảnh: Phương Huy — CC0, qua Wikimedia Commons",
  "/uploads/external/445a26698d7c.jpg": "Ảnh: Hiep Nguyen hiepng — CC0, qua Wikimedia Commons",
  "/uploads/external/c22f445fad1d.jpg": "Ảnh: trungydang — CC BY 3.0, qua Wikimedia Commons",
  "/uploads/external/5fe6aafe9f6e.jpg": "Ảnh: Daderot — CC0, qua Wikimedia Commons",
  "/uploads/external/d8e432383a80.jpg": "Ảnh: Anne and David from Kent, England UK — Public domain, qua Wikimedia Commons",
  "/uploads/external/4315c3094d30.jpg": "Ảnh: Balon Greyjoy — CC0, qua Wikimedia Commons",
  "/uploads/external/07e5d5530756.jpg": "Ảnh: Diego Delso — CC BY-SA 3.0, qua Wikimedia Commons",
  "/uploads/external/efb5de76d2ab.jpg": "Ảnh: Alpha from Melbourne, Australia — CC BY-SA 2.0, qua Wikimedia Commons",
  "/uploads/external/dea9d1957905.jpg": "Ảnh: Phương Huy — CC0, qua Wikimedia Commons",
  "/uploads/external/253070044ab3.jpg": "Ảnh: Phương Huy — CC0, qua Wikimedia Commons",
  "/uploads/external/fbaa80ad4819.jpg": "Ảnh: Andy Li — CC0, qua Wikimedia Commons",
};

/**
 * Attribution line for a locally hosted image, or null when none is required.
 * CC BY-SA obliges us to credit the author wherever the image appears, and the
 * obligation follows the image rather than the host.
 */
export function creditFor(src: string | undefined | null): string | null {
  if (!src) return null;
  const withoutQuery = src.split('?')[0];
  return CREDITS[withoutQuery] ?? null;
}
